name: Deploy PHP Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 192.168.100.35
          username: mark-joseph
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/mywebsite
            git pull origin main
